server:
  port: 8081


spring:
  application:
    name: SpringBase
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: 123456
    url: jdbc:mysql://localhost:3306/pandora?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

